//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WLVPN.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WLVPN.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Applications.
        /// </summary>
        internal static string AddApplications {
            get {
                return ResourceManager.GetString("AddApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This domain already exists, please enter a different domain..
        /// </summary>
        internal static string AddDomainAlreadyExistsError {
            get {
                return ResourceManager.GetString("AddDomainAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid domain format.
        /// </summary>
        internal static string AddDomainValidationError {
            get {
                return ResourceManager.GetString("AddDomainValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow local network interfaces when connected..
        /// </summary>
        internal static string AllowLanInterfaces {
            get {
                return ResourceManager.GetString("AllowLanInterfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option controls local network interfaces availability when you&apos;re connected to a VPN server. If the option is off, the app will block all other network interfaces on your computer. This will prevent you from data leaking, for example, while torrenting, but will block the ability to access your LAN resources..
        /// </summary>
        internal static string AllowLanInterfacesDescription {
            get {
                return ResourceManager.GetString("AllowLanInterfacesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application already added: {0}.
        /// </summary>
        internal static string ApplicationAlreadyAdded {
            get {
                return ResourceManager.GetString("ApplicationAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Startup.
        /// </summary>
        internal static string AppStartup {
            get {
                return ResourceManager.GetString("AppStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not automatically connect.
        /// </summary>
        internal static string AppStartupOption1 {
            get {
                return ResourceManager.GetString("AppStartupOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to last connected server.
        /// </summary>
        internal static string AppStartupOption2 {
            get {
                return ResourceManager.GetString("AppStartupOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to fastest server.
        /// </summary>
        internal static string AppStartupOption3 {
            get {
                return ResourceManager.GetString("AppStartupOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        internal static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connects to the best protocol among ones listed below. Can fallback to the other protocols..
        /// </summary>
        internal static string AutomaticDescription {
            get {
                return ResourceManager.GetString("AutomaticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Reconnect.
        /// </summary>
        internal static string AutoReconnect {
            get {
                return ResourceManager.GetString("AutoReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the VPN is unexpectedly disconnected, this will attempt to reconnect the VPN. .
        /// </summary>
        internal static string AutoReconnectDescription {
            get {
                return ResourceManager.GetString("AutoReconnectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN Status Change.
        /// </summary>
        internal static string BalloonNotificationTitle {
            get {
                return ResourceManager.GetString("BalloonNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Available.
        /// </summary>
        internal static string BestAvailable {
            get {
                return ResourceManager.GetString("BestAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block LAN access when Kill Switch is enabled.
        /// </summary>
        internal static string BlockLanToolTip {
            get {
                return ResourceManager.GetString("BlockLanToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block LAN Traffic.
        /// </summary>
        internal static string BlockLANTraffic {
            get {
                return ResourceManager.GetString("BlockLANTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your language:.
        /// </summary>
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Portal.
        /// </summary>
        internal static string ClientPortal {
            get {
                return ResourceManager.GetString("ClientPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will take you to the applications main web site..
        /// </summary>
        internal static string ClientPortalHelpText {
            get {
                return ResourceManager.GetString("ClientPortalHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Application.
        /// </summary>
        internal static string CloseApplication {
            get {
                return ResourceManager.GetString("CloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What close action should the application perform?.
        /// </summary>
        internal static string CloseDialogDescription {
            get {
                return ResourceManager.GetString("CloseDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Close Action.
        /// </summary>
        internal static string CloseDialogTitle {
            get {
                return ResourceManager.GetString("CloseDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing.
        /// </summary>
        internal static string Closing {
            get {
                return ResourceManager.GetString("Closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Application.
        /// </summary>
        internal static string ClosingOption1 {
            get {
                return ResourceManager.GetString("ClosingOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide to Tray.
        /// </summary>
        internal static string ClosingOption2 {
            get {
                return ResourceManager.GetString("ClosingOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Dialog and Ask.
        /// </summary>
        internal static string ClosingOption3 {
            get {
                return ResourceManager.GetString("ClosingOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now connected to {0}..
        /// </summary>
        internal static string ConnectedBalloon {
            get {
                return ResourceManager.GetString("ConnectedBalloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectivity.
        /// </summary>
        internal static string Connectivity {
            get {
                return ResourceManager.GetString("Connectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+C.
        /// </summary>
        internal static string ConnectShortcut {
            get {
                return ResourceManager.GetString("ConnectShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connects to the default/selected server.
        /// </summary>
        internal static string ConnectShortcutDescription {
            get {
                return ResourceManager.GetString("ConnectShortcutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Diagnostics Data.
        /// </summary>
        internal static string CopyDiagnosticsData {
            get {
                return ResourceManager.GetString("CopyDiagnosticsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current IP: {0}.
        /// </summary>
        internal static string CurrentIP {
            get {
                return ResourceManager.GetString("CurrentIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Protocol.
        /// </summary>
        internal static string CurrentProtocol {
            get {
                return ResourceManager.GetString("CurrentProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Downloaded.
        /// </summary>
        internal static string DataDownloaded {
            get {
                return ResourceManager.GetString("DataDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Uploaded.
        /// </summary>
        internal static string DataUploaded {
            get {
                return ResourceManager.GetString("DataUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable DNS leak protection..
        /// </summary>
        internal static string DisableDNSLeakProtection {
            get {
                return ResourceManager.GetString("DisableDNSLeakProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable IPv6 leak protection..
        /// </summary>
        internal static string DisableIPv6LeakProtection {
            get {
                return ResourceManager.GetString("DisableIPv6LeakProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Shortcuts.
        /// </summary>
        internal static string DisableShortcuts {
            get {
                return ResourceManager.GetString("DisableShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been disconnected from {0}..
        /// </summary>
        internal static string DisconnectedBalloon {
            get {
                return ResourceManager.GetString("DisconnectedBalloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting.
        /// </summary>
        internal static string Disconnecting {
            get {
                return ResourceManager.GetString("Disconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+D.
        /// </summary>
        internal static string DisconnectShortcut {
            get {
                return ResourceManager.GetString("DisconnectShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect the VPN.
        /// </summary>
        internal static string DisconnectShortcutDescription {
            get {
                return ResourceManager.GetString("DisconnectShortcutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        internal static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domains.
        /// </summary>
        internal static string Domains {
            get {
                return ResourceManager.GetString("Domains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Application.
        /// </summary>
        internal static string DuplicateApplication {
            get {
                return ResourceManager.GetString("DuplicateApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Shortcuts.
        /// </summary>
        internal static string EnableShortCut {
            get {
                return ResourceManager.GetString("EnableShortCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Shortcuts.
        /// </summary>
        internal static string EnableShortcuts {
            get {
                return ResourceManager.GetString("EnableShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Speech Feedback.
        /// </summary>
        internal static string EnableSpeech {
            get {
                return ResourceManager.GetString("EnableSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Split Tunneling.
        /// </summary>
        internal static string EnableSplitTunneling {
            get {
                return ResourceManager.GetString("EnableSplitTunneling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connects VPN to the currently selected location..
        /// </summary>
        internal static string HelpTextConnectButton {
            get {
                return ResourceManager.GetString("HelpTextConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnects the VPN..
        /// </summary>
        internal static string HelpTextDisconnectButton {
            get {
                return ResourceManager.GetString("HelpTextDisconnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takes you to the web site to resend your password.
        /// </summary>
        internal static string HelpTextForgotPassword {
            get {
                return ResourceManager.GetString("HelpTextForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current state of the Kill Switch Property.   See the General Settings tab for control of this..
        /// </summary>
        internal static string HelpTextKillSwitch {
            get {
                return ResourceManager.GetString("HelpTextKillSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Tab contains the ability to modify all of the settings.
        /// </summary>
        internal static string HelpTextMainTabControlName {
            get {
                return ResourceManager.GetString("HelpTextMainTabControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password for the user login.
        /// </summary>
        internal static string HelpTextPassword {
            get {
                return ResourceManager.GetString("HelpTextPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currently selected VPN protocol.
        /// </summary>
        internal static string HelpTextProtocol {
            get {
                return ResourceManager.GetString("HelpTextProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This allows you to search for a location to connect to..
        /// </summary>
        internal static string HelpTextSearch {
            get {
                return ResourceManager.GetString("HelpTextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts the sign in process.
        /// </summary>
        internal static string HelpTextSignIn {
            get {
                return ResourceManager.GetString("HelpTextSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takes you to the web site to create an account.
        /// </summary>
        internal static string HelpTextSignUp {
            get {
                return ResourceManager.GetString("HelpTextSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the username to use to log in with.
        /// </summary>
        internal static string HelpTextUserName {
            get {
                return ResourceManager.GetString("HelpTextUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide to Tray.
        /// </summary>
        internal static string HideToTray {
            get {
                return ResourceManager.GetString("HideToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+H.
        /// </summary>
        internal static string HomeShortcut {
            get {
                return ResourceManager.GetString("HomeShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Tab.
        /// </summary>
        internal static string HomeShortcutDescription {
            get {
                return ResourceManager.GetString("HomeShortcutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IKEv2.
        /// </summary>
        internal static string IKEv2 {
            get {
                return ResourceManager.GetString("IKEv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers highly stable security, especially when switching networks or reconnecting. Faster than other protocols, but only supported on limited platforms..
        /// </summary>
        internal static string Ikev2Description {
            get {
                return ResourceManager.GetString("Ikev2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include All Subdomains.
        /// </summary>
        internal static string IncludeAllSubdomains {
            get {
                return ResourceManager.GetString("IncludeAllSubdomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1.
        /// </summary>
        internal static string InformationShortcut {
            get {
                return ResourceManager.GetString("InformationShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Tab.
        /// </summary>
        internal static string InformationShortcutDescription {
            get {
                return ResourceManager.GetString("InformationShortcutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        internal static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string InstallRepair {
            get {
                return ResourceManager.GetString("InstallRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenVPN requires TAP Adapter being installed. Select &quot;Install&quot; to try to install it..
        /// </summary>
        internal static string InstallRepairTAP {
            get {
                return ResourceManager.GetString("InstallRepairTAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid application selected.
        /// </summary>
        internal static string InvalidApplication {
            get {
                return ResourceManager.GetString("InvalidApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current IP.
        /// </summary>
        internal static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill Switch.
        /// </summary>
        internal static string KillSwitch {
            get {
                return ResourceManager.GetString("KillSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isolate this PC from the Internet if the VPN is cut off.
        /// </summary>
        internal static string KillSwitchToolTip {
            get {
                return ResourceManager.GetString("KillSwitchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changes aren&apos;t applied until the next launch, do you wish to save your changes?.
        /// </summary>
        internal static string LanguageChangeInfo {
            get {
                return ResourceManager.GetString("LanguageChangeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Shortcuts.
        /// </summary>
        internal static string ListOfShortcuts {
            get {
                return ResourceManager.GetString("ListOfShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to disconnect from {0}, {1} and connect to {2}, {3}?.
        /// </summary>
        internal static string LocationChangeConfirmation {
            get {
                return ResourceManager.GetString("LocationChangeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging In.
        /// </summary>
        internal static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Out.
        /// </summary>
        internal static string LoggingOut {
            get {
                return ResourceManager.GetString("LoggingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Screen.
        /// </summary>
        internal static string LoginUserControlTitle {
            get {
                return ResourceManager.GetString("LoginUserControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Window.
        /// </summary>
        internal static string MainScreenTitle {
            get {
                return ResourceManager.GetString("MainScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string MainTabControlName {
            get {
                return ResourceManager.GetString("MainTabControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize Application.
        /// </summary>
        internal static string MaximizeApplication {
            get {
                return ResourceManager.GetString("MaximizeApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Box Popup.
        /// </summary>
        internal static string MessageBoxScreenTitle {
            get {
                return ResourceManager.GetString("MessageBoxScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize Application.
        /// </summary>
        internal static string MinimizeApplication {
            get {
                return ResourceManager.GetString("MinimizeApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No app has been added yet.
        /// </summary>
        internal static string NoAppAdded {
            get {
                return ResourceManager.GetString("NoAppAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No domain has been added yet.
        /// </summary>
        internal static string NoDomainAdded {
            get {
                return ResourceManager.GetString("NoDomainAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize User Screen.
        /// </summary>
        internal static string NotAuthorizedUserControlTitle {
            get {
                return ResourceManager.GetString("NotAuthorizedUserControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Help.
        /// </summary>
        internal static string OpenHelp {
            get {
                return ResourceManager.GetString("OpenHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings.
        /// </summary>
        internal static string OpenSettings {
            get {
                return ResourceManager.GetString("OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenVPN.
        /// </summary>
        internal static string OpenVPN {
            get {
                return ResourceManager.GetString("OpenVPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides the best security. It may be slower than other protocols due to its stronger security. OpenVPN is also good choice when other  protocols are not available due to firewall restrictions..
        /// </summary>
        internal static string OpenVPNDescription {
            get {
                return ResourceManager.GetString("OpenVPNDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers directory is missing..
        /// </summary>
        internal static string OpenVpnNotSupportedTapInstall {
            get {
                return ResourceManager.GetString("OpenVpnNotSupportedTapInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Manually.
        /// </summary>
        internal static string PickManually {
            get {
                return ResourceManager.GetString("PickManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string ProgressSuffix {
            get {
                return ResourceManager.GetString("ProgressSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will attempt to reconnect in {0} seconds.
        /// </summary>
        internal static string ReconnectAfter {
            get {
                return ResourceManager.GetString("ReconnectAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnecting.
        /// </summary>
        internal static string Reconnecting {
            get {
                return ResourceManager.GetString("Reconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of retries:.
        /// </summary>
        internal static string ReconnectTries {
            get {
                return ResourceManager.GetString("ReconnectTries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scramble.
        /// </summary>
        internal static string Scramble {
            get {
                return ResourceManager.GetString("Scramble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scramble adds obfuscation capability to OpenVPN, allowing it to bypass network traffic sensors which aim to detect usage of a VPN and block it..
        /// </summary>
        internal static string ScrambleDescription {
            get {
                return ResourceManager.GetString("ScrambleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+S.
        /// </summary>
        internal static string SettingsShortcut {
            get {
                return ResourceManager.GetString("SettingsShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Tab.
        /// </summary>
        internal static string SettingsShortcutDescription {
            get {
                return ResourceManager.GetString("SettingsShortcutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ShortcutDescription {
            get {
                return ResourceManager.GetString("ShortcutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enable or disable shortcuts, go to settings..
        /// </summary>
        internal static string ShortcutsEnableHelp {
            get {
                return ResourceManager.GetString("ShortcutsEnableHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of available shortcuts is available on Help page..
        /// </summary>
        internal static string ShortcutsReference {
            get {
                return ResourceManager.GetString("ShortcutsReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Shortcuts.
        /// </summary>
        internal static string ShortcutsTitle {
            get {
                return ResourceManager.GetString("ShortcutsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Window.
        /// </summary>
        internal static string ShowWindow {
            get {
                return ResourceManager.GetString("ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an Account? SIGN UP.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Tunneling.
        /// </summary>
        internal static string SplitTunneling {
            get {
                return ResourceManager.GetString("SplitTunneling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Startup.
        /// </summary>
        internal static string SystemStartup {
            get {
                return ResourceManager.GetString("SystemStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start application when user logs in.
        /// </summary>
        internal static string SystemStartupOption1 {
            get {
                return ResourceManager.GetString("SystemStartupOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide application on startup.
        /// </summary>
        internal static string SystemStartupOption2 {
            get {
                return ResourceManager.GetString("SystemStartupOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reboot is required to finish TAP driver installation..
        /// </summary>
        internal static string TabDriverRebootRequired {
            get {
                return ResourceManager.GetString("TabDriverRebootRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string TabInformation {
            get {
                return ResourceManager.GetString("TabInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string TabInformationHelp {
            get {
                return ResourceManager.GetString("TabInformationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        internal static string TabInformationLicenses {
            get {
                return ResourceManager.GetString("TabInformationLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string TabSettingsConnection {
            get {
                return ResourceManager.GetString("TabSettingsConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        internal static string TabSettingsDiagnostics {
            get {
                return ResourceManager.GetString("TabSettingsDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string TabSettingsGeneral {
            get {
                return ResourceManager.GetString("TabSettingsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Tunneling.
        /// </summary>
        internal static string TabSettingsSplitTunneling {
            get {
                return ResourceManager.GetString("TabSettingsSplitTunneling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenVPN TAP Adapter.
        /// </summary>
        internal static string TapAdapter {
            get {
                return ResourceManager.GetString("TapAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install TAP driver..
        /// </summary>
        internal static string TapDriverFail {
            get {
                return ResourceManager.GetString("TapDriverFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAP driver was successfully installed..
        /// </summary>
        internal static string TapDriverSuccess {
            get {
                return ResourceManager.GetString("TapDriverSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAP Drivers Installer.
        /// </summary>
        internal static string TapInstaller {
            get {
                return ResourceManager.GetString("TapInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TAP device has not been installed on this computer. 
        ///The TAP device must be installed for OpenVPN to connect. 
        ///
        ///Would you like to install one now?..
        /// </summary>
        internal static string TapNotInstalledText {
            get {
                return ResourceManager.GetString("TapNotInstalledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAP Device is Not Installed.
        /// </summary>
        internal static string TapNotInstalledTitle {
            get {
                return ResourceManager.GetString("TapNotInstalledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file chosen: {0}.
        /// </summary>
        internal static string UnsupportedFileChosen {
            get {
                return ResourceManager.GetString("UnsupportedFileChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string UpdaterInstall {
            get {
                return ResourceManager.GetString("UpdaterInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates available for this release..
        /// </summary>
        internal static string UpdaterNoUpdatesAvailable {
            get {
                return ResourceManager.GetString("UpdaterNoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes.
        /// </summary>
        internal static string UpdaterReleaseNotes {
            get {
                return ResourceManager.GetString("UpdaterReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of {0} is available!
        ///The new version is {1} (You currently have version {2}).
        /// </summary>
        internal static string UpdaterWindowDescription {
            get {
                return ResourceManager.GetString("UpdaterWindowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Update Service.
        /// </summary>
        internal static string UpdaterWindowTitle {
            get {
                return ResourceManager.GetString("UpdaterWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        internal static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Diagnostics Files.
        /// </summary>
        internal static string ViewDiagnosticsButton {
            get {
                return ResourceManager.GetString("ViewDiagnosticsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External IP Address.
        /// </summary>
        internal static string VisibleIPAddress {
            get {
                return ResourceManager.GetString("VisibleIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible Location.
        /// </summary>
        internal static string VisibleLocation {
            get {
                return ResourceManager.GetString("VisibleLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN Protocol.
        /// </summary>
        internal static string VpnProtocol {
            get {
                return ResourceManager.GetString("VpnProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WireGuard.
        /// </summary>
        internal static string WireGuard {
            get {
                return ResourceManager.GetString("WireGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The newest, fastest and most resilient VPN protocol, with state-of-the-art security..
        /// </summary>
        internal static string WireGuardDescription {
            get {
                return ResourceManager.GetString("WireGuardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
