//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VpnSDK.WLVpn.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VpnSDK.WLVpn.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating.
        /// </summary>
        public static string AUTHENTICATING {
            get {
                return ResourceManager.GetString("AUTHENTICATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Available.
        /// </summary>
        public static string BEST_AVAILABLE {
            get {
                return ResourceManager.GetString("BEST_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Location.
        /// </summary>
        public static string CHANGE_LOCATION_BUTTON {
            get {
                return ResourceManager.GetString("CHANGE_LOCATION_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cipher Level:.
        /// </summary>
        public static string CIPHER_LEVEL {
            get {
                return ResourceManager.GetString("CIPHER_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CITY {
            get {
                return ResourceManager.GetString("CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Application.
        /// </summary>
        public static string CLOSE_DIALOG_QUIT_BUTTON {
            get {
                return ResourceManager.GetString("CLOSE_DIALOG_QUIT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cipher:.
        /// </summary>
        public static string CONNECTED_ENCRYPTION {
            get {
                return ResourceManager.GetString("CONNECTED_ENCRYPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public IP:.
        /// </summary>
        public static string CONNECTED_PUBLIC_IP_HEADER {
            get {
                return ResourceManager.GetString("CONNECTED_PUBLIC_IP_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible Location:.
        /// </summary>
        public static string CONNECTED_VISIBLE_LOCATION_HEADER {
            get {
                return ResourceManager.GetString("CONNECTED_VISIBLE_LOCATION_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible Location Changed.
        /// </summary>
        public static string CONNECTED_VISIBLE_LOCATION_HEADER_CHANGED {
            get {
                return ResourceManager.GetString("CONNECTED_VISIBLE_LOCATION_HEADER_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string CONNECTING {
            get {
                return ResourceManager.GetString("CONNECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string COUNTRY {
            get {
                return ResourceManager.GetString("COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now shown as {0}..
        /// </summary>
        public static string CURRENT_VISIBLE_LOCATION {
            get {
                return ResourceManager.GetString("CURRENT_VISIBLE_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont log me out!.
        /// </summary>
        public static string DIALOG_ACTION_CANCEL {
            get {
                return ResourceManager.GetString("DIALOG_ACTION_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will force you to log in again.  Do you want to continue?.
        /// </summary>
        public static string DIALOG_ACTION_DESCRIPTION {
            get {
                return ResourceManager.GetString("DIALOG_ACTION_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string DIALOG_ACTION_OK {
            get {
                return ResourceManager.GetString("DIALOG_ACTION_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue and log me out!.
        /// </summary>
        public static string DIALOG_ACTION_OK_LOGOUT {
            get {
                return ResourceManager.GetString("DIALOG_ACTION_OK_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to log out of your account!.
        /// </summary>
        public static string DIALOG_ACTION_TITLE {
            get {
                return ResourceManager.GetString("DIALOG_ACTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting.
        /// </summary>
        public static string DISCONNECTING {
            get {
                return ResourceManager.GetString("DISCONNECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured .
        /// </summary>
        public static string ERROR_OCCURED {
            get {
                return ResourceManager.GetString("ERROR_OCCURED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing TAP Driver.
        /// </summary>
        public static string INSTALLING_TAP_DRIVER {
            get {
                return ResourceManager.GetString("INSTALLING_TAP_DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        public static string IP_UPDATING_TEXT {
            get {
                return ResourceManager.GetString("IP_UPDATING_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string LOAD {
            get {
                return ResourceManager.GetString("LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging out.
        /// </summary>
        public static string LOGGING_OUT {
            get {
                return ResourceManager.GetString("LOGGING_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LOGIN_EMAILBOX_HINT {
            get {
                return ResourceManager.GetString("LOGIN_EMAILBOX_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Email/Password?.
        /// </summary>
        public static string LOGIN_FORGOT_EMAIL_PASSWORD {
            get {
                return ResourceManager.GetString("LOGIN_FORGOT_EMAIL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Username/Password?.
        /// </summary>
        public static string LOGIN_FORGOT_USERNAME_PASSWORD {
            get {
                return ResourceManager.GetString("LOGIN_FORGOT_USERNAME_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LOGIN_PASSWORDBOX_HINT {
            get {
                return ResourceManager.GetString("LOGIN_PASSWORDBOX_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string LOGIN_SIGNIN_BUTTON {
            get {
                return ResourceManager.GetString("LOGIN_SIGNIN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string LOGIN_SIGNUP_BUTTON {
            get {
                return ResourceManager.GetString("LOGIN_SIGNUP_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LOGIN_USERNAMEBOX_HINT {
            get {
                return ResourceManager.GetString("LOGIN_USERNAMEBOX_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now connected to {0}, {1}..
        /// </summary>
        public static string NOTIFICATION_CONNECTED_TEXT {
            get {
                return ResourceManager.GetString("NOTIFICATION_CONNECTED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been disconnected from {0}, {1}..
        /// </summary>
        public static string NOTIFICATION_DISCONNECTED_TEXT {
            get {
                return ResourceManager.GetString("NOTIFICATION_DISCONNECTED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        public static string PING {
            get {
                return ResourceManager.GetString("PING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnecting.
        /// </summary>
        public static string RECONNECTING {
            get {
                return ResourceManager.GetString("RECONNECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Startup.
        /// </summary>
        public static string SETTINGS_APPLICATION_STARTUP {
            get {
                return ResourceManager.GetString("SETTINGS_APPLICATION_STARTUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not automatically connect.
        /// </summary>
        public static string SETTINGS_APPLICATION_STARTUP_OPTION1 {
            get {
                return ResourceManager.GetString("SETTINGS_APPLICATION_STARTUP_OPTION1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to last connected server.
        /// </summary>
        public static string SETTINGS_APPLICATION_STARTUP_OPTION2 {
            get {
                return ResourceManager.GetString("SETTINGS_APPLICATION_STARTUP_OPTION2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Reconnect if a VPN is disconnected unexpectedly..
        /// </summary>
        public static string SETTINGS_AUTO_RECONNECT {
            get {
                return ResourceManager.GetString("SETTINGS_AUTO_RECONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing.
        /// </summary>
        public static string SETTINGS_CLOSING {
            get {
                return ResourceManager.GetString("SETTINGS_CLOSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close button hides the application to tray.
        /// </summary>
        public static string SETTINGS_CLOSING_OPTION2 {
            get {
                return ResourceManager.GetString("SETTINGS_CLOSING_OPTION2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show dialog and ask.
        /// </summary>
        public static string SETTINGS_CLOSING_OPTION3 {
            get {
                return ResourceManager.GetString("SETTINGS_CLOSING_OPTION3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        public static string SETTINGS_DIAGNOSTICS {
            get {
                return ResourceManager.GetString("SETTINGS_DIAGNOSTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill Switch cuts your connection on the Internet when your VPN connection fails..
        /// </summary>
        public static string SETTINGS_GENERAL_KILLSWITCH_DESCRIPTION {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_KILLSWITCH_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notifications in taskbar.
        /// </summary>
        public static string SETTINGS_GENERAL_NOTIFICATIONS {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_NOTIFICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill Switch.
        /// </summary>
        public static string SETTINGS_KILL_SWITCH {
            get {
                return ResourceManager.GetString("SETTINGS_KILL_SWITCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string SETTINGS_OTHER {
            get {
                return ResourceManager.GetString("SETTINGS_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IKEv2.
        /// </summary>
        public static string SETTINGS_PROTOCOL_IKEV2 {
            get {
                return ResourceManager.GetString("SETTINGS_PROTOCOL_IKEV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers highly stable security, especially when switching networks or 
        ///reconnecting. .
        /// </summary>
        public static string SETTINGS_PROTOCOL_IKEV2_DESC {
            get {
                return ResourceManager.GetString("SETTINGS_PROTOCOL_IKEV2_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenVPN.
        /// </summary>
        public static string SETTINGS_PROTOCOL_OPENVPN {
            get {
                return ResourceManager.GetString("SETTINGS_PROTOCOL_OPENVPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides the best security. It may be slower than other protocols due 
        ///to its stronger security. OpenVPN is also good choice when other 
        ///protocols are not available due to firewall restrictions..
        /// </summary>
        public static string SETTINGS_PROTOCOL_OPENVPN_DESC {
            get {
                return ResourceManager.GetString("SETTINGS_PROTOCOL_OPENVPN_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scramble.
        /// </summary>
        public static string SETTINGS_PROTOCOL_OPENVPN_SCRAMBLE {
            get {
                return ResourceManager.GetString("SETTINGS_PROTOCOL_OPENVPN_SCRAMBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scramble adds obfuscation capability to OpenVPN, allowing it to bypass 
        ///network traffic sensors which aim to detect usage of a VPN and block it..
        /// </summary>
        public static string SETTINGS_PROTOCOL_OPENVPN_SCRAMBLE_INFO {
            get {
                return ResourceManager.GetString("SETTINGS_PROTOCOL_OPENVPN_SCRAMBLE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Startup.
        /// </summary>
        public static string SETTINGS_SYSTEM_STARTUP {
            get {
                return ResourceManager.GetString("SETTINGS_SYSTEM_STARTUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start application when User logs in.
        /// </summary>
        public static string SETTINGS_SYSTEM_STARTUP_OPTION1 {
            get {
                return ResourceManager.GetString("SETTINGS_SYSTEM_STARTUP_OPTION1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide application on startup.
        /// </summary>
        public static string SETTINGS_SYSTEM_STARTUP_OPTION2 {
            get {
                return ResourceManager.GetString("SETTINGS_SYSTEM_STARTUP_OPTION2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string SETTINGS_TAB_ABOUT {
            get {
                return ResourceManager.GetString("SETTINGS_TAB_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string SETTINGS_TAB_CONNECTION {
            get {
                return ResourceManager.GetString("SETTINGS_TAB_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SETTINGS_TAB_GENERAL {
            get {
                return ResourceManager.GetString("SETTINGS_TAB_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string SETTINGS_TAB_LICENSES {
            get {
                return ResourceManager.GetString("SETTINGS_TAB_LICENSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string SETTINGS_TAB_LOGS {
            get {
                return ResourceManager.GetString("SETTINGS_TAB_LOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string SETTINGS_UPDATES {
            get {
                return ResourceManager.GetString("SETTINGS_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Connected.
        /// </summary>
        public static string TASKBAR_CONNECTED {
            get {
                return ResourceManager.GetString("TASKBAR_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current IP: {0}.
        /// </summary>
        public static string TASKBAR_CURRENT_IP {
            get {
                return ResourceManager.GetString("TASKBAR_CURRENT_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Disconnected.
        /// </summary>
        public static string TASKBAR_DISCONNECTED {
            get {
                return ResourceManager.GetString("TASKBAR_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Window.
        /// </summary>
        public static string TASKBAR_HIDE_WINDOW {
            get {
                return ResourceManager.GetString("TASKBAR_HIDE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Window.
        /// </summary>
        public static string TASKBAR_SHOW_WINDOW {
            get {
                return ResourceManager.GetString("TASKBAR_SHOW_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} is now available (you have {2})..
        /// </summary>
        public static string UPDATE_DIALOG_DESCRIPTION {
            get {
                return ResourceManager.GetString("UPDATE_DIALOG_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of {0} is available!.
        /// </summary>
        public static string UPDATE_DIALOG_HEADER {
            get {
                return ResourceManager.GetString("UPDATE_DIALOG_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install update.
        /// </summary>
        public static string UPDATE_DIALOG_INSTALL {
            get {
                return ResourceManager.GetString("UPDATE_DIALOG_INSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes:.
        /// </summary>
        public static string UPDATE_DIALOG_RELEASE_NOTES {
            get {
                return ResourceManager.GetString("UPDATE_DIALOG_RELEASE_NOTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind me later.
        /// </summary>
        public static string UPDATE_DIALOG_REMIND {
            get {
                return ResourceManager.GetString("UPDATE_DIALOG_REMIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this version.
        /// </summary>
        public static string UPDATE_DIALOG_SKIP {
            get {
                return ResourceManager.GetString("UPDATE_DIALOG_SKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available!.
        /// </summary>
        public static string UPDATE_DIALOG_TITLE {
            get {
                return ResourceManager.GetString("UPDATE_DIALOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VERSION {
            get {
                return ResourceManager.GetString("VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string VPN_BUTTON_CONNECT {
            get {
                return ResourceManager.GetString("VPN_BUTTON_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string VPN_BUTTON_DISCONNECT {
            get {
                return ResourceManager.GetString("VPN_BUTTON_DISCONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string WINDOW_BUTTON_SETTINGS {
            get {
                return ResourceManager.GetString("WINDOW_BUTTON_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string WINDOW_BUTTON_SIGNOUT {
            get {
                return ResourceManager.GetString("WINDOW_BUTTON_SIGNOUT", resourceCulture);
            }
        }
    }
}
